### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [peejaybee/NyanWallpaper#1]
Apache 2 ?

**Comment by peejaybee** [comment]
Hmm.  I haven't even looked at this in a while.  I will put that on it.

Let me make one thing clear, though.   I don't own any rights to Nyan Cat, and as of the time I last modified this project, the owner was issuing DMCA takedowns on any Nyan Cat apps on the Play store.

**Comment by AndroidDeveloperLB** [comment]
Thank you!
