### ISSUE TITLE
How to keep aspect ratio of the gif animation?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [peejaybee/NyanWallpaper#2]
If it doesn't fit 100% in the screen, it seems stretched...
Do you know how to do any of the following with it:
1. center-crop 
2. stretch to fit width/height
3. set as original size, centered, and stretch to fit width/height only if too large.

**Comment by peejaybee** [comment]
Don't know, sorry.  I haven't really touched this in years.

**Comment by AndroidDeveloperLB** [comment]
Too bad.
